### ISSUE TITLE
Moving widgets with a width greater than one wont move across one space.

### ISSUE THREAD

**Issue by WigglesTehPro** [dsmorse/gridster.js#52] opened 2016-05-04 09:28 UTC
These two images below show the issue.

![gridstererrorpart1](https://cloud.githubusercontent.com/assets/11716445/15010092/2d089478-11e2-11e6-8b74-4e329637bfc7.PNG)

![image](https://cloud.githubusercontent.com/assets/11716445/15010073/1d8c78a2-11e2-11e6-8543-c375daa8ce1f.png)

**Comment by robertadsoft** [comment] 2016-05-20 05:20
I'm experiencing the same issue. After playing with the widget a little the smaller position becomes available again.

**Comment by DaTebe** [comment] 2016-08-14 14:43
Is there a solution to this "problem". E.G. in Kibana it works very well. But they use the ducksboard version 0.5.6

**Comment by andreityuhai** [comment] 2016-08-24 13:58
It's duplicate of #44

**Closed** 2016-11-18 11:41 UTC
